### ISSUE TITLE
Character unexpected rotation problem.

### ISSUE THREAD

**Issue by erimkurt** [mikhomak/Erbium#3]
First of all, I like your character system. Thanks for share it. 
I try to test the character with a simple rigid cube. When it hit the cube, the character starts spinning. If I lock the rotation y-axis, working fine. Why do we need to unfreeze the rotation y-axis?
![Screen Shot 2564-06-03 at 11 26 20](https://user-images.githubusercontent.com/5739115/120589012-66795980-c462-11eb-9a7c-e4aa2e70c5bf.png)

https://user-images.githubusercontent.com/5739115/120589520-2a92c400-c463-11eb-85d9-246ce7438e61.mov

**Comment by mikhomak** [comment]
Hey mate!
I'm glad you liked it!
While interacting with other rigid gameobjects that can happen, however they are some solutions to this:
1) freeze Y axis as you did
2) Play around with angular drag/mass on the character
3) You can set the rigidbody of the character to be kinematic, that way the physics will be affected only through scripts and animations (It's usually a good option to do with the animation based characters)
