### ISSUE TITLE
i can't find hitbox 

### ISSUE THREAD

**Issue by imad-123** [mikhomak/Erbium#9]
first thanks for this project 
but where i can find hitbox in the project

**Comment by mikhomak** [comment]
Hey!
You have to add trigger collision to your model and then add [this script](https://github.com/mikhomak/Erbium/blob/master/Erbium/Assets/Scripts/Characters/Hitbox/Hitbox.cs)
![image](https://user-images.githubusercontent.com/37109805/129685036-46220783-3393-4912-8180-a1bcc9d3e02b.png)   
![image](https://user-images.githubusercontent.com/37109805/129685116-62035ac6-4d2b-4800-80ad-0edf4e7370e5.png)



[you can find more here](https://github.com/mikhomak/Erbium/wiki/Hitbox)

**Comment by imad-123** [comment]
yes i will try it thanks for your replay
